color0 #404752
color1 #ffb4ab
color2 #a2c9ff
color3 #adc8f1
color4 #f0b0ff
color5 #a2c9ff
color6 #adc8f1
color7 #e0e2ea
color8 #8a919d
color9 #ffb4ab
color10 #a2c9ff
color11 #adc8f1
color12 #f0b0ff
color13 #a2c9ff
color14 #adc8f1
color15 #e0e2ea

cursor                #e0e2ea
cursor_text_color     #000000
background            #000000
foreground            #e0e2ea
selection_foreground  #c0c7d4
selection_background  #404752
active_border_color   #a2c9ff
inactive_border_color #323944
url_color             #a2c9ff

active_tab_foreground   #00315b
active_tab_background   #a2c9ff
inactive_tab_foreground #c0c7d4
inactive_tab_background #323944
cursor_trail_color      #c0c7d4
