color0 #434653
color1 #ffb4ab
color2 #b2c5ff
color3 #b7c5f4
color4 #f2afff
color5 #b2c5ff
color6 #b7c5f4
color7 #e2e2eb
color8 #8d909e
color9 #ffb4ab
color10 #b2c5ff
color11 #b7c5f4
color12 #f2afff
color13 #b2c5ff
color14 #b7c5f4
color15 #e2e2eb

cursor                #e2e2eb
cursor_text_color     #000000
background            #000000
foreground            #e2e2eb
selection_foreground  #c3c6d5
selection_background  #434653
active_border_color   #b2c5ff
inactive_border_color #363945
url_color             #b2c5ff

active_tab_foreground   #002b74
active_tab_background   #b2c5ff
inactive_tab_foreground #c3c6d5
inactive_tab_background #363945
cursor_trail_color      #c3c6d5
