color0 #534438
color1 #ffb4ab
color2 #ffcb9e
color3 #ebbe98
color4 #d1dc76
color5 #ffb877
color6 #ebbe98
color7 #eee0d6
color8 #a08d7f
color9 #ffb4ab
color10 #ffcb9e
color11 #ebbe98
color12 #d1dc76
color13 #ffb877
color14 #ebbe98
color15 #eee0d6

cursor                #eee0d6
cursor_text_color     #19120d
background            #19120d
foreground            #eee0d6
selection_foreground  #d8c3b3
selection_background  #534438
active_border_color   #ffcb9e
inactive_border_color #534438
url_color             #ffcb9e

active_tab_foreground   #4b2700
active_tab_background   #ffcb9e
inactive_tab_foreground #d8c3b3
inactive_tab_background #534438
cursor_trail_color      #d8c3b3
