-- Generated by nwg-displays on 2026-09-13 at 08:52:23. Do not edit manually.

hl.monitor({
	output = "eDP-1",
	mode = "2880x1920@60.0",
	position = "0x0",
	scale = 1.5,
	vrr = 1,
})
hl.monitor({
	output = "DP-4",
	mode = "800x600@60.32",
	position = "1920x0",
	scale = 1,
	vrr = 0,
	mirror = "eDP-1",
})
