[audio]
enable_overdrive = true
enable_sounds = true
notification_sound = "/home/beepew/.config/noctalia/notification.mp3"

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_radius = 8
    capsule_thickness = 0.69999998807907104
    center = [ "taskbar" ]
    end = [ "group:g2", "group:g1" ]
    margin_ends = 250
    padding = 10
    radius = 10
    radius_top_left = 15
    radius_top_right = 15
    scale = 0.95000000670552254
    start = [ "workspaces" ]
    thickness = 30
    widget_spacing = 10

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "volume", "brightness", "bluetooth", "network", "battery", "clock" ]
        opacity = 1.0
        padding = 6.0
        radius = 8.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "tray", "widget", "notifications" ]
        opacity = 1.0
        padding = 6.0
        radius = 8.0

[calendar]
enabled = true

    [calendar.account.personal_google]
    name = "Personal Calendar"
    type = "google"

[control_center]
sidebar = "full"
sidebar_section = "full"
width = 870

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1600.0
    cy = 828.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "calendar"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 173.0
    cy = 963.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 112.0
    cy = 830.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

[dock]
active_monitor_only = true
cross_axis_padding = 2
icon_size = 24
item_spacing = 0
main_axis_padding = 2

[hooks]
started = "until ping -c 1 8.8.8.8 >/dev/null 2>&1; do sleep 2; done; notify-send \"You have $(( $(checkupdates 2>/dev/null | wc -l) + $(yay -Qua 2>/dev/null | wc -l) + $(flatpak remote-ls --updates 2>/dev/null | wc -l) )) updates waiting for you!\""

[idle]
behavior_order = [ "Sleep Warning", "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior."Sleep Warning"]
    action = "command"
    command = "notify-send \"Warning!\" \"Your computer will fall asleep in 30 seconds!\""
    enabled = false
    resume_command = "notify-send \"Wuh- huh?\" \"I'm awake!\""
    timeout = 530.0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.79999998211860657
blurred_desktop = true
tint_intensity = 0.53999998793005943

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 816.0
    cx = 960.0
    cy = 1018.0
    output = "HDMI-A-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 1098.0
    output = "eDP-1"
    placement_height = 1280.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 160.0
    box_width = 496.0
    cx = 960.0
    cy = 232.0
    output = "HDMI-A-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 112.0
    box_width = 256.0
    cx = 416.0
    cy = 1064.0
    output = "HDMI-A-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        bands = 32
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 240.0
    box_width = 288.0
    cx = 1520.0
    cy = 992.0
    output = "HDMI-A-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 128.0
    box_width = 256.0
    cx = 416.0
    cy = 936.0
    output = "HDMI-A-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "volume"

[nightlight]
enabled = true

[notification]
max_visible = 5
offset_y = 10

[osd]
orientation = "vertical"
position = "bottom_center"
position_vertical = "center_right"

[plugin_settings."whyoolw/dropwall"]
copy_to_wallpaper_dir = true

[plugins]
enabled = [ "thepunkoff/pomodoro", "alexander/screen-toolkit", "whyoolw/dropwall", "tadomika_ari/w-engine" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
avatar_path = "/home/beepew/.pfp.jpg"
password_style = "random"
polkit_agent = true
time_format = "{:%I:%M}"

    [shell.launcher]
    categories = false

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    list_item_background = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screen_corners]
    enabled = true

    [shell.session]
    grid = true

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "5"
        variant = "destructive"

        [[shell.session.actions]]
        action = "command"
        command = "systemctl reboot --firmware-setup"
        countdown_seconds = 0.0
        enabled = true
        label = "Reboot to UEFI"
        variant = "primary"

[theme]
builtin = "Ayu"
community_palette = "Oxocarbon"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kitty", "qt" ]
    community_ids = [ "pywalfox", "discord", "obsidian", "yazi" ]

        [theme.templates.user.btop]
        input_path = "~/.config/noctalia/templates/btop.theme"
        output_path = "~/.config/btop/themes/matugen.theme"
        post_hook = "pkill -SIGUSR2 btop || true"

        [theme.templates.user.neovim]
        input_path = "~/.config/noctalia/templates/nvim-colors.json"
        output_path = "~/.config/nvim/colors.json"
        post_hook = "pkill -SIGUSR1 nvim"

        [theme.templates.user.starship]
        input_path = "~/.config/noctalia/templates/starship-colors.toml"
        output_path = "~/.config/starship.toml"

        [theme.templates.user.websites-mozilla]
        input_path = "~/.config/noctalia/templates/firefox-colors.css"
        output_path = "~/.mozilla/firefox/colors.css"
        post_hook = "sh ~/.config/noctalia/scripts/install_website_colors.sh"

[wallpaper]
directory = "/home/beepew/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/beepew/Pictures/Wallpapers/Cat/Kittyboard.png"

    [wallpaper.last]
    path = "/home/beepew/Pictures/Wallpapers/Cat/Kittyboard.png"

    [wallpaper.monitors.DP-1]
    path = "/home/beepew/Pictures/Wallpapers/Kitty.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/beepew/Pictures/Wallpapers/Kitty.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/beepew/Pictures/Wallpapers/Cat/Kittyboard.png"

[widget.clock]
format = "{:%I:%M}"

[widget.network]
show_label = false

[widget.taskbar]
anchor = true
icon_scale = 1.3500000000000001
item_spacing = 10
show_all_outputs = true
show_window_title = true

[widget.tray]
drawer = true

[widget.widget]
type = "thepunkoff/pomodoro:widget"

[widget.workspaces]
focused_output_only = true
label_source = "name"
pill_scale = 0.75
style = "minimal"
