# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0e2ea"

# Title color for boxes
theme[title]="#a2c9ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#adc8f1"

# Background color of selected item in processes box
theme[selected_bg]="#a2c9ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#00315b"

# Color of inactive/disabled text
theme[inactive_fg]="#c0c7d4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f0b0ff"

# Cpu box outline color
theme[cpu_box]="#8a919d"

# Memory/disks box outline color
theme[mem_box]="#8a919d"

# Net up/down box outline color
theme[net_box]="#8a919d"

# Processes box outline color
theme[proc_box]="#8a919d"

# Box divider line and small boxes line color
theme[div_line]="#404752"

# Temperature graph colors
theme[temp_start]="#adc8f1"
theme[temp_mid]="#a2c9ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#adc8f1"
theme[cpu_mid]="#a2c9ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#adc8f1"
theme[free_mid]=""
theme[free_end]="#2f4a6d"

# Mem/Disk cached meter
theme[cached_start]="#f0b0ff"
theme[cached_mid]=""
theme[cached_end]="#c879df"

# Mem/Disk available meter
theme[available_start]="#a2c9ff"
theme[available_mid]=""
theme[available_end]="#429bf8"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#adc8f1"
theme[download_mid]="#a2c9ff"
theme[download_end]="#f0b0ff"

# Upload graph colors
theme[upload_start]="#adc8f1"
theme[upload_mid]="#a2c9ff"
theme[upload_end]="#f0b0ff"